# The plugin for each supported theme
_tmux_theme_plugin_map:
  solarized: seebi/tmux-colors-solarized

# The base path where the light & dark plugin colours live
_tmux_theme_dark_notify_base:
  solarized: "$HOME/.config/tmux/plugins/tmux-colors-solarized"

# The full path to the light & dark colour files which dark-notify will use
_tmux_theme_dark_notify_color_name:
  solarized:
    light: "$HOME/.config/tmux/plugins/tmux-colors-solarized/tmuxcolors-light.conf"
    dark: "$HOME/.config/tmux/plugins/tmux-colors-solarized/tmuxcolors-dark.conf"

tmux_theme_dark_notify_path_light: "{{ _tmux_theme_dark_notify_color_name[tmux_theme]['light'] }}"
tmux_theme_dark_notify_path_dark: "{{ _tmux_theme_dark_notify_color_name[tmux_theme]['dark'] }}"

tmux_theme_plugin: "{{ _tmux_theme_plugin_map[tmux_theme] }}"
