# When this is true, try to install necessary packages for full clipboard
# support, for example xsel, wl-copy or (in the future) osc.
tmux_install_clipboard: false

# A supported theme. Automatically switches between light & dark. Current
# options:
# - solarized
tmux_theme: solarized
