---
- name: Install tmux package
  become: true
  ansible.builtin.package:
    name: tmux
  when: ansible_distribution != 'MacOSX'

- name: Install clipboard dependencies
  become: true
  # TODO: Support more methods, e.g. osc
  # TODO: Support more distros, e.g. Ubuntu & MacOS
  # TODO: Test how to support remote systems (i.e. servers), e.g. via osc?
  when: ansible_distribution == 'Archlinux' and tmux_install_clipboard
  ansible.builtin.package:
    name:
      - wl-clipboard  # Wayland
      - xsel  # X

- name: Install tmux package
  ansible.builtin.package:
    name: tmux
  when: ansible_distribution == 'MacOSX'

# Necessary for the erikw/tmux-dark-notify plugin
- name: Install dark-notify for macOS package
  ansible.builtin.package:
    name: cormacrelf/tap/dark-notify
  when: ansible_distribution == 'MacOSX'

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.config/tmux/plugins/tpm
    version: master
    update: false

- name: Set up tmux config
  ansible.builtin.file:
    state: link
    dest: ~/.config/tmux/tmux.conf
    src: "{{ role_path }}/files/tmux.conf"
  when: ansible_connection == 'local'

- name: Set up tmux config by copying
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.config/tmux/tmux.conf
  when: ansible_connection != 'local'
