---
- name: Validate tmux_install_method
  ansible.builtin.fail:
    msg: >-
      Invalid tmux_install_method '{{ tmux_install_method }}'.
      Supported values are 'default' and 'github_release'.
  when: tmux_install_method not in ['default', 'github_release']

- name: Install tmux package
  become: true
  ansible.builtin.package:
    name: tmux
  when: ansible_facts.distribution != 'MacOSX' and tmux_install_method != 'github_release'

- name: Install tmux from official binaries
  ansible.builtin.include_tasks: install_github_release.yml
  when: ansible_facts.distribution != 'MacOSX' and tmux_install_method == 'github_release'

- name: Install tmux package
  ansible.builtin.package:
    name: tmux
  when: ansible_facts.distribution == 'MacOSX'

# Necessary for the erikw/tmux-dark-notify plugin
- name: Install dark-notify for macOS package
  ansible.builtin.package:
    name: cormacrelf/tap/dark-notify
  when: ansible_facts.distribution == 'MacOSX'

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.config/tmux/plugins/tpm
    version: master
    update: false

- name: Install catppuccin themes
  ansible.builtin.git:
    # Using my own fork since upstream uses `set -o` which means switching
    # themes isn't possible.
    repo: https://github.com/Javex/catppuccin-tmux.git
    dest: ~/.config/tmux/plugins/catppuccin/tmux
    version: main
    update: false

- name: Set up tmux config
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.config/tmux/tmux.conf
    force: true
