- name: Apply git config options
  ansible.builtin.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_dict: "{{ gitconfig_defaults | ansible.builtin.combine(gitconfig_extra) }}"
