- name: Install neovim on Ubuntu
  become: true
  block:
    
    - name: Add neovim ppa to get recent version
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable

    - name: Install neovim from ppa
      ansible.builtin.apt:
        name:
          - neovim
          - ripgrep
          - npm
          - python3-dev
          - python3-pip
        update_cache: true
