- name: Install neovim packages
  become: true
  community.general.pacman:
    name:
      - neovim
      - ripgrep
      - npm
  when: ansible_distribution == 'Archlinux'

- name: Include Ubuntu install
  ansible.builtin.include_tasks: install_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install neovim packages on MacOS
  community.general.homebrew:
    name:
      - neovim
  when: ansible_distribution == 'MacOSX'

- name: Clone NvChad repo
  ansible.builtin.git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    depth: 1
    version: v2.0

- name: Install custom config by linking
  ansible.builtin.file:
    state: link
    path: ~/.config/nvim/lua/custom
    src: "{{ role_path }}/files/custom"
  when: ansible_connection == 'local'

# Yes it sucks having to copy each file by hand but both copy and synchronize
# aren't great because they don't do well with --diff (among other things)
- name: Install custom config by copying
  when: ansible_connection != 'local'
  block:
    - name: Create directories for config files
      ansible.builtin.file:
        state: directory
        path: ~/.config/nvim/lua/custom/configs
    - name: Copy individual files
      ansible.builtin.copy:
        src: "custom/{{ item }}"
        dest: "~/.config/nvim/lua/custom/{{ item }}"
      loop:
        - chadrc.lua
        - init.lua
        - mappings.lua
        - plugins.lua
        - configs/lspconfig.lua
