- name: Install neovim packages
  become: true
  community.general.pacman:
    name:
      - neovim
      - ripgrep
      - npm
  when: ansible_distribution == 'Archlinux'

- name: Include Ubuntu install
  ansible.builtin.include_tasks: install_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install neovim packages on MacOS
  community.general.homebrew:
    name:
      - neovim
  when: ansible_distribution == 'MacOSX'

- name: Clone repo
  ansible.builtin.git:
    repo: git@github.com:Javex/neovim.git
    dest: ~/.config/nvim
    version: main
    remote: github
